Add ability to name src blocks and auto-collapse code blocks.
stig/ox-jira.el pull request #31
Opened 2017-03-09 08:04 UTC by rymndhng

Solves #30

2017-03-20 13:32 UTC, stig commented
Hello, thank you for your PR! I like it! (I'm afraid I totally missed the notification about this, so sorry for the wait.) That said, I've got a couple comments / questions:

1. Where did you find out about the `collapse` option? It's not listed here: https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=advanced -- is it available in all versions of JIRA?

2. It feels like you should be using `#+CAPTION:` rather than `#+NAME:` as per http://orgmode.org/manual/Images-and-tables.html#Images-and-tables

2017-03-20 22:38 UTC, rymndhng commented
> Where did you find out about the collapse option? It's not listed here: https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=advanced -- is it available in all versions of JIRA?

I actually found this using the confluence code block macro (the doc site is down right now...). I did test it on JIRA and it worked as well.

> It feels like you should be using #+CAPTION: rather than #+NAME: as per http://orgmode.org/manual/Images-and-tables.html#Images-and-tables

Sounds right -- Will update the PR

2017-03-21 03:04 UTC, rymndhng commented
@stig I've updated the PR. Not sure if I have the best implementation for building the caption text (it came back as a sequence of characters).

2017-03-21 14:38 UTC, stig requested changes
Hello! This seems good to me, though please rename the variables  to use a `ox-jira` prefix rather than `org-jira` as org-jira refers to https://github.com/ahungry/org-jira rather than this project :-)

2017-03-21 14:38 UTC, stig commented on ox-jira.el
> +(defgroup org-export-jira nil
This need to be `ox-export-jira` I think. `org-jira` is a differet package :-)

2017-03-21 14:38 UTC, stig commented on ox-jira.el
> +(defcustom org-jira-src-collapse-threshold 30
`ox-jira-src-collapse-threshold` please

2017-03-21 14:38 UTC, stig commented on ox-jira.el
> +  :group 'org-export-jira
`ox-export-jira`

2017-03-21 14:38 UTC, stig commented on ox-jira.el
> +  '((:src-collapse-threshold nil nil org-jira-src-collapse-threshold))
`ox-jira-src-...` please

2017-03-26 01:06 UTC, rymndhng commented
@stig I've updated the PR.

2017-03-26 07:36 UTC, stig approved these changes

2017-03-26 07:47 UTC, merged

2017-03-26 07:47 UTC, stig commented
Thank you!